# Laboratorium 14 - PLIK OVERRIDE (nadpisywania)
# Autor: Bartosz Owczarczyk
#
# Lab 14 - override: porty (specyficzne dla srodowiska)

services:
  nginx:
    ports:
      - "4001:80"

  phpmyadmin:
    ports:
      - "6001:80"
